// src/lib/component/Propuestas.svelte
<script lang="ts">
  import propuestas from "../data/propuestas";
  import PropuestaLi from "./PropuestaLi.svelte";

  interface Propuesta {
    title: string;
    description: string;
    date: string;
    enProgreso: boolean;
  }
  const propuestasList: Propuesta[] = propuestas;
</script>

<ul class=" space-y-4">
  {#each propuestasList as propuesta}
    {#if !propuesta.date}
      <PropuestaLi {propuesta} />
    {/if}
  {/each}
</ul>

// src/components/Propuestas.tsx
import React from 'react';
import PropuestaLi from './PropuestaLi';

const Propuestas: React.FC = () => {
  return (
    <section className="py-2">
      <header className="text-2xl font-bold">
        <h1>Propuestas</h1>
      </header>
      <ul className="py-4 flex flex-col gap-4">
        <PropuestaLi title="Propuesta 1" description="Desc" />
        <PropuestaLi title="Propuesta 2" description="Desc 2" />
      </ul>
    </section>
  );
};

export default Propuestas;
